### ISSUE TITLE
bug: fast move on the screen

### ISSUE THREAD

**Issue by xhzengAIB** [GabrielAlva/Swift-Prompts#1]
![bug](https://cloud.githubusercontent.com/assets/1969908/7041040/3d1ceca6-de08-11e4-8df8-6d821c654889.gif)

**Comment by GabrielAlva** [comment]
Hi Jack, thanks for taking the time to make the gif to illustrate the bug. I will push a fix soon however if you'd like to make a pull request I can merge it so you can be listed as a contributor to the project.

**Comment by jchomali** [comment]
Hi, my last pull request fixes this bug.

**Comment by GabrielAlva** [comment]
Hey, I merged your pull request, thanks for submitting it!
