### ISSUE TITLE
UIImageEffects issue using vImage_buffer

### ISSUE THREAD

**Issue by jfoc2009** [GabrielAlva/Swift-Prompts#4]
.../devLib/Swift-Prompts/Swift-Prompts/UIImageEffects.swift:174:31: Cannot find an initializer for type 'vImage_Buffer' that accepts an argument list of type '(data: UnsafeMutablePointer<Void>, height: Int, width: Int, rowBytes: Int)'.

After searching about this issue, I have tried:
=== 1 ====
var vBuffer = vImage_Buffer(
data: CGBitmapContextGetData(context),
height: CGBitmapContextGetHeight(context), 
width: CGBitmapContextGetWidth(context), 
rowBytes: CGBitmapContextGetBytesPerRow(context))
                
return vBuffer
==== 2====

instead of using let for data, height, width, rowBytes, I changed to var, because vImage_Buffer is using unsafe pointer.

==========

But the result is the same.

In my project, I'm using (as reference to Swift-Prompt folders) the 3 files: UIImageEffects.swift, SwiftPrompts.swift, SwiftPromptsView.swift.

xcode 6.3
![captura de tela 2015-04-20 as 00 26 29](https://cloud.githubusercontent.com/assets/2215244/7223202/f3f837d4-e6f3-11e4-9d30-bb8e6413f049.png)

**Comment by orlandoamorim** [comment]
try this:

let width = UInt(CGBitmapContextGetWidth(context))
let height = UInt(CGBitmapContextGetHeight(context))

change the width and the height

**Comment by gnatok** [comment]
I already put PR with that fix

**Comment by GabrielAlva** [comment]
Hi, I merged the pull request with the fix from gnatok
